common_params:
  # Common plugin settings to use with the `plugins` key.
  - &common_plugins
    - automattic/bash-cache#2.11.0

steps:
  - label: "Lint & Checkstyle"
    key: "lint_and_checkstyle"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew lintRelease checkstyle
    artifact_paths:
      - "**/build/reports/lint-results**.*"
      - "**/build/reports/checkstyle/checkstyle.*"

  - label: "Test"
    key: "test"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew test

  - label: "Publish to S3 Maven"
    depends_on:
      - "lint_and_checkstyle"
      - "test"
    plugins: *common_plugins
    command: |
      cp gradle.properties-example gradle.properties
      ./gradlew \
          prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
          publish
